### ISSUE TITLE
Keys in repo

### ISSUE THREAD

**Issue by zacanger** [aiya000/mastodon.vim#1]
Should [this](https://github.com/aiya000/mastodon.vim/blob/master/plugin/mastodon.vim#L9) be here? Maybe a test key/secret, but would it be safer just in an env var?

**Comment by aiya000** [comment]
Thanks :smile:  
I think it's really problem too ...  
But I don't want each user takes to get API tokens :joy:  
mmm... What should I do...

Would have you an idea ? :joy_cat:

**Comment by mattn** [comment]
@zacanger what do you worry about? client_id/client_secret is the key to prove the client not user.

**Comment by aiya000** [comment]
@zacanger @mattn Thanks 😋  
Coincidentally, it was avoided by [this commit](https://github.com/aiya000/mastodon.vim/blhttps://github.com/aiya000/mastodon.vim/blob/develop/autoload/mastodon/account.vim#L50ob/develop/autoload/mastodon/account.vim#L50).

This way registers mastodon.vim for each user account. ...:thinking:

**Comment by zacanger** [comment]
Ah right on, I'll close then :)

**Comment by aiya000** [comment]
:smile:
